### ISSUE TITLE
Bonemealing a flower doesn't work with a dispenser

### ISSUE THREAD

**Issue by Inferis** [Trikzon/flourish#15] opened 2024-03-06 17:14 UTC
The bedrock flower mechanic allows for bonemealing a flower to spread other flowers using a dispenser dispensing bonemeal from the bottom of the grass block. This works in vanilla for an empty grass block which will spread grass and local flowers. 

It would be cool that Flourish would support the dispenser behavior too. Would make for a lovely mechanic for a flower farm!

**Comment by Trikzon** [comment] 2024-03-06 18:24
It does work. Just to make sure, I just tested it on the latest version (v20.4.1 on MC 1.20.4). 
![image](https://github.com/Trikzon/flourish/assets/29845000/2fcc3076-d3b5-4bac-9451-525edea7b922)

Is it not working for you? If it isn't, could you give more information?

**Comment by Trikzon** [comment] 2024-03-06 18:25
Closing because I cannot reproduce the issue, but please reopen it if you have more information. Thanks for using the mod :D

**Closed as not planned by Trikzon** 2024-03-06 18:25 UTC

**Comment by Inferis** [comment] 2024-03-06 18:43
Ah, you have to do it like that. I tried with a dispenser under the grass block.
I'll try again! Thanks for the quick response!
